// <auto-generated />
using System;
using KioskGame.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace KioskGame.Api.Migrations
{
    [DbContext(typeof(GameDbContext))]
    [Migration("20260216050132_AddPrizes")]
    partial class AddPrizes
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.0");

            modelBuilder.Entity("KioskGame.Api.Models.PlayHistory", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsWin")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("PlayedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("PlayerId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PrizeCode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("PrizeId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PrizeName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("PlayHistories");
                });

            modelBuilder.Entity("KioskGame.Api.Models.Player", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<bool>("HasWonGift")
                        .HasColumnType("INTEGER");

                    b.Property<DateOnly>("LastPlayDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("PlaysRemaining")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("SessionExpiresAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("SessionStartedAtUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Players");
                });

            modelBuilder.Entity("KioskGame.Api.Models.Prize", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Weight")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("Prizes");
                });
#pragma warning restore 612, 618
        }
    }
}
